version: '3.8'

services:
  # --- Backend Service (NestJS) ---
  backend:
    build:
      context: ./backend
    container_name: nurse_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    networks:
      - internal_network
    depends_on:
      - db

  # --- Frontend Service (React) ---
  frontend:
    build:
      context: ./frontend
    container_name: nurse_frontend
    restart: unless-stopped
    networks:
      - internal_network
    depends_on:
      - backend

  # --- Nginx Service (Reverse Proxy) ---
  nginx:
    image: nginx:1.25-alpine
    container_name: nurse_nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - internal_network
    depends_on:
      - frontend
      - backend

  # --- Database Service (PostgreSQL) ---
  db:
    image: postgres:15-alpine
    container_name: nurse_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-nursesystem}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-nursesystem123}
      POSTGRES_DB: ${POSTGRES_DB:-nurse_scheduling}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal_network

volumes:
  postgres_data:

networks:
  internal_network:
    driver: bridge